#
# template to enable metrics-collector and prometheus services
#      

# define virtual network to give fixed IP for loki used by the logging-driver for all containers
networks:
  vpcbr: # virtual network name
    driver: bridge
    ipam:
     config: # here, we define our ip space
       - subnet: 10.5.0.0/24
         gateway: 10.5.0.1

# this is a YAML anchor to avoid repetition
x-logging: &logging
  logging:
    driver: loki
    options: # note: the ip is the ip we will assign later to loki in this file
      loki-url: "http://10.5.0.2:3100/loki/api/v1/push"
      mode: non-blocking
      max-buffer-size: 4m
      loki-retries: "3"
      max-size: "10m"
      max-file: 1

services:

  # The Loki database for storing logs.
  loki:
    <<: *logging
    container_name: loki
    image: WIS2BOX-RELEASE
    restart: always
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - loki-data:/loki
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
    networks:
      vpcbr: # this is the place where we assign the static ipv4 address
        ipv4_address: 10.5.0.2
      default:
  wis2node-monitor-china:
    build: 
      context: ./mqtt-metrics-collector
    restart: unless-stopped
    environment:
      - BROKER_HOST=gb.wis.cma.cn
      - BROKER_PORT=8883
      - BROKER_USERNAME=everyone
      - BROKER_PASSWORD=everyone
      - BROKER_TRANSPORT=tcp
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
  wis2node-monitor-brazil:
    <<: *logging
    build: 
      context: ./mqtt-metrics-collector
    restart: unless-stopped
    environment:
      - BROKER_HOST=globalbroker.inmet.gov.br
      - BROKER_PORT=443
      - BROKER_USERNAME=everyone
      - BROKER_PASSWORD=everyone
      - BROKER_TRANSPORT=websockets
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}

  wis2node-monitor-france:
    <<: *logging
    build: 
      context: ./mqtt-metrics-collector
    restart: unless-stopped
    environment:
      - BROKER_HOST=globalbroker.meteo.fr
      - BROKER_PORT=443
      - BROKER_USERNAME=everyone
      - BROKER_PASSWORD=everyone
      - BROKER_TRANSPORT=websockets
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}

  wis2node-monitor-usa:
    <<: *logging
    build: 
      context: ./mqtt-metrics-collector
    restart: unless-stopped
    environment:
      - BROKER_HOST=wis2broker.globaldata.nws.noaa.gov
      - BROKER_PORT=8883
      - BROKER_USERNAME=everyone
      - BROKER_PASSWORD=everyone
      - BROKER_TRANSPORT=tcp
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}

  prometheus:
    image: prom/prometheus:v2.37.0
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=365d'
      - '--log.level=warn'
  
  grafana:
    image: grafana/grafana:12.3
    restart: unless-stopped
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/home.json
    depends_on:
      - prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${WIS2NODE_MONITOR_HOST}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  traefik:
    image: traefik:v2.11
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
    volumes:
      - traefik-letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  prometheus-data:
  traefik-letsencrypt:
  grafana-data: