{
 "title": "Number of Active WIS2 Nodes",
 "tags": [ "preconfigured" ],
 "time": { "from": "now-7d", "to": "now-1h" },
 "panels": [
  {
   "title": "Number of active WIS2 Nodes by Earth System Discipline",
   "type": "timeseries",
   "description": "Count of unique centre-id with at least one notification in 24-hours, breakdown by Earth System Discipline as extracted from the WIS2-topic the notification was published on",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(discipline) (sum by(data_policy, discipline, centre_id) (increase(wis2node_monitor_origin_volume_received_total{broker_host=\"globalbroker.inmet.gov.br\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of active WIS2 Nodes by Data Policy",
   "type": "timeseries",
   "description": "Count of unique centre-id with at least one notification in 24-hours, breakdown by data-policy as extracted from the WIS2-topic the notification was published on",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by(data_policy) (sum by(data_policy, data_policy, centre_id) (increase(wis2node_monitor_origin_volume_received_total{broker_host=\"globalbroker.inmet.gov.br\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of active WIS2 Nodes by sub-topics below Earth System Discipline",
   "type": "timeseries",
   "description": "Count of unique centre-id with at least one notification in 24-hours, breakdown by subtopics below Earth System Discipline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by(subtopics) (sum by(data_policy, subtopics, centre_id) (increase(wis2node_monitor_origin_volume_received_total{broker_host=\"globalbroker.inmet.gov.br\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of active WIS2 Nodes by notification-generated-by",
   "type": "timeseries",
   "description": "Count of unique centre-id with at least one notification in 24-hours, breakdown by software as extracted from the \"generated_by\"-property embedded in the notification",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count by(generated_by) (sum by(data_policy, generated_by, centre_id) (increase(wis2node_monitor_origin_volume_received_total{broker_host=\"globalbroker.inmet.gov.br\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}