{
 "title": "WIS2 NWP monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "WIS2 data volume published on weather/prediction/forecast/medium-range/deterministic/#",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(centre_id) (increase(wis2node_monitor_forecast_origin_volume_received_total{broker_host=\"gb.wis.cma.cn\", topic_level10=\"deterministic\"}[1m]))/60.",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WIS2 data volume published on weather/prediction/forecast/medium-range/probabilistic/#",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(centre_id) (increase(wis2node_monitor_forecast_origin_volume_received_total{broker_host=\"gb.wis.cma.cn\", topic_level10=\"probabilistic\", centre_id!=\"de-dwd\"}[1m])) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ECMWF: WIS2 data volume published on weather/prediction/forecast/medium-range/#",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(topic_level10) (increase(wis2node_monitor_forecast_origin_volume_received_total{broker_host=\"gb.wis.cma.cn\", centre_id=\"int-ecmwf\"}[1m]))/60.",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Canada ECCC: WIS2 data volume published on weather/prediction/forecast/medium-range/#",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(topic_level10) (increase(wis2node_monitor_forecast_origin_volume_received_total{broker_host=\"gb.wis.cma.cn\", centre_id=\"ca-eccc-msc\"}[1m]))/60.",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "China CMA: WIS2 data volume published on weather/prediction/forecast/medium-range/#",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(topic_level10) (increase(wis2node_monitor_forecast_origin_volume_received_total{broker_host=\"gb.wis.cma.cn\", centre_id=\"cn-cma\"}[1m]))/60.",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UK MET Office: WIS2 data volume published on weather/prediction/forecast/medium-range/#",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(topic_level10) (increase(wis2node_monitor_forecast_origin_volume_received_total{broker_host=\"gb.wis.cma.cn\", centre_id=\"uk-metoffice-wmc\"}[1m]))/60.",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}