{
 "title": "WIS2 NWP Monitoring",
 "tags": [ "preconfigured" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "broker_host",
    "query": {
     "query": "label_values(wis2node_monitor_forecast_origin_messages_received_total,broker_host)"
    }
   },
   {
    "name": "subtopic1",
    "query": {
     "query": "label_values(wis2node_monitor_forecast_origin_volume_received_total,subtopic1)"
    }
   },
   {
    "name": "subtopic2",
    "query": {
     "query": "label_values(wis2node_monitor_forecast_origin_volume_received_total,subtopic2)"
    }
   },
   {
    "name": "subtopic3",
    "query": {
     "query": "label_values(wis2node_monitor_forecast_origin_volume_received_total,subtopic3)"
    }
   },
   {
    "name": "subtopic4",
    "query": {
     "query": "label_values(wis2node_monitor_forecast_origin_volume_received_total,subtopic4)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Data volume published per hour, by centre-id",
   "type": "timeseries",
   "description": "Hourly increase of volume published  on origin/a/wis2/+/weather/prediction/# breakdown by WIS2 centre-id as derived from the WIS2-topic, volume based on the length of the canonical-link as advertised in the WIS2 notification",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(centre_id) (increase(wis2node_monitor_forecast_origin_volume_received_total{broker_host=\"$broker_host\", subtopic1=~\"$subtopic1\", subtopic2=~\"$subtopic2\", subtopic3=~\"$subtopic3\", subtopic4=~\"$subtopic4\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Data Volume published per hour by centre-id and metadata-id",
   "type": "table",
   "description": "Hourly increase of volume published  on origin/a/wis2/+/weather/prediction/# breakdown by WIS2 centre-id as derived from the WIS2-topic, volume based on the length of the canonical-link as advertised in the WIS2 notification",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n  sum by(centre_id, subtopic1, subtopic2, subtopic3, subtopic4) (\r\n    increase(wis2node_monitor_forecast_origin_volume_received_total{\r\n      broker_host=\"$broker_host\",\r\n      subtopic1=~\"$subtopic1\",\r\n      subtopic2=~\"$subtopic2\",\r\n      subtopic3=~\"$subtopic3\",\r\n      subtopic4=~\"$subtopic4\"\r\n    }[1h])\r\n  )[$__range:1h]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notifications published per hour, by centre-id",
   "type": "timeseries",
   "description": "Hourly increase of number of notifications published  on origin/a/wis2/+/weather/prediction/# breakdown by WIS2 centre-id as derived from the WIS2-topic",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(centre_id) (increase(wis2node_monitor_forecast_origin_messages_received_total{broker_host=\"$broker_host\", subtopic1=~\"$subtopic1\", subtopic2=~\"$subtopic2\", subtopic3=~\"$subtopic3\", subtopic4=~\"$subtopic4\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}